### ISSUE TITLE
FPCUPdeluxe fails to install FPC for Raspberry PICO on Windows 7

### ISSUE THREAD

**Issue by M0GXB** [michael-ring/pico-fpcexamples#10]
(I had previously used it to successfully instal FPC+Lazarus for 64 bit Windows on Win7 system).
Using the exact instructions from the WiKi i.e. clicking the PICO button and running it, it eventually fails like this:
fpcupdeluxe: ERROR: Lazarus Native Installer (BuildModule: Lazbuild): H:\FPC\PICO\lazarus\Makefile not found. Severe error. Should not happen. Aborting build Lazbuild.
ERROR: Fpcupdeluxe fatal error !
Sequencer (UserIDE): Failure running fpcupdeluxe: error executing sequence UserIDE
Sequencer (Lazarus): Failure running fpcupdeluxe: error executing sequence Lazarus
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default

Earlier in the install the rot set in here I think....
fpcupdeluxe: Executing: H:\FPC\PICO\fpcbootstrap\git\cmd\git.exe show -s --format=%s%b (working dir: H:\FPC\PICO\lazarus)
fpcupdeluxe: Executing: H:\FPC\PICO\fpcbootstrap\git\cmd\git.exe log -1 --pretty=format:%h (working dir: H:\FPC\PICO\lazarus)
fpcupdeluxe: Executing: H:\FPC\PICO\fpcbootstrap\git\cmd\git.exe describe --tags --long --always (working dir: H:\FPC\PICO\lazarus)
fpcupdeluxe: Executing: H:\FPC\PICO\fpcbootstrap\git\cmd\git.exe log -g -1 --pretty=oneline (working dir: H:\FPC\PICO\lazarus)
fpcupdeluxe: Executing: H:\FPC\PICO\fpcbootstrap\git\cmd\git.exe describe --tags --all --long --always (working dir: H:\FPC\PICO\lazarus)
fpcupdeluxe: ERROR: Lazarus Native Installer (GetModule: Lazarus): Could not get version of Lazarus sources. Expect severe errors.

The trouble with this kind of thing is that by 50 years of expereince as a systems programmer just doesn't help as I have n idea how this is being driven etc.

**Comment by michael-ring** [comment]
Expired
