### ISSUE TITLE
PWM Example

### ISSUE THREAD

**Issue by dryas** [michael-ring/pico-fpcexamples#12]
Hey, 

first of all thanks a lot for your great work!

I wonder if it would be possible to get an example for the PWM usage of the RP2040?

Thanks a lot,

Ben

**Comment by michael-ring** [comment]
I have now ported the PWM module (have not yet checked it in) let me know if you want to test what I have right now. What I am doing is work in progress as I also want to switch to latest Pico SDK.

**Comment by michael-ring** [comment]
Pushed my changes to picosdk1.5.1 branch

**Comment by dryas** [comment]
Thanks a lot!
