### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by cobaltBlueCloud** [michael-ring/pico-fpcexamples#4]
Hi, Michael!

Just a briefly 'thank you' for your examples!
Allready used TurboPascal/Lazarus/mikroPascal-for-AVR, but 
recently jumped into the world of the PICO using you examples! 

Kind regards! Marcel

**Comment by cobaltBlueCloud** [comment]
In case of a question recarding an example programm, what is the best place for asking? Kind regards. Marcel

**Comment by michael-ring** [comment]
Glad I could help!
When you see issues with the examples then create a bug here, for general discussion better use the embedded board in freepascal forum:

https://forum.lazarus.freepascal.org/index.php?board=79.0

**Comment by cobaltBlueCloud** [comment]
Tnx!
